# Circumscribed circle
circumscribedCircle:
	g++ -std=c++23 ./circumscribedCircle.cpp -o ../../../build/circumscribedCircle

# Illegal edges
illegalEdges:
	g++ -std=c++23 ./illegalEdges.cpp -o ../../../build/illegalEdges

# Monotone polygon
monotonePolygon:
	g++ -std=c++23 ./monotonePolygon.cpp -o ../../../build/monotonePolygon

# Points and semiplanes
pointsAndSemiplanes:
	g++ -std=c++23 ./pointsAndSemiplanes.cpp -o ../../../build/pointsAndSemiplanes

# Semiplanes intersection
semiplanesIntersection:
	g++ -std=c++23 ./semiplanesIntersection.cpp -o ../../../build/semiplanesIntersection

# Intersection points
intersectionPoints:
	g++ -std=c++23 ./intersectionPoints.cpp -o ../../../build/intersectionPoints
	
# Utilities
clean:
	rm -rf ../../../build/*