# Circumscribed circle
circumscribedCircle:
	g++ -std=c++23 ./circumscribedCircle.cpp -o ../../../build/circumscribedCircle

# Illegal edges
illegalEdges:
	g++ -std=c++23 ./illegalEdges.cpp -o ../../../build/illegalEdges

# Monotone polygon
monotonePolygon:
	g++ -std=c++23 ./monotonePolygon.cpp -o ../../../build/monotonePolygon

# Utilities
clean:
	rm -rf ../../../build/*