# Orientation test
orientationTest:
	g++ -std=c++23 ./orientationTest.cpp -o ../../../build/orientationTest

# Roby
roby:
	g++ -std=c++23 ./roby.cpp -o ../../../build/roby

# Convex hull
convexHull:
	g++ -std=c++23 ./convexHull.cpp -o ../../../build/convexHull

# TSP Convex hull
tspConvexHull:
	g++ -std=c++23 ./tspConvexHull.cpp -o ../../../build/tspConvexHull

# Utilities
clean:
	rm -rf ../../../build/*